name: Require Semver Label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels
        run: |
          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "PR labels: $labels"

          if echo "$labels" | grep -E '^(major|minor|patch)$' > /dev/null; then
            echo "✅ Valid semver label found"
          else
            echo "❌ PR must have one of these labels: major, minor, patch"
            exit 1
          fi
