name: Require Semver Label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')

          echo "PR labels: $labels"

          if echo "$labels" | grep -E '^(major|minor|patch)$' > /dev/null; then
            echo "✅ Valid semver label found"
          else
            echo "❌ PR must have one of these labels: major, minor, patch"
            exit 1
          fi
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
